CREATE TABLE raw_teams (
    season_team_id character varying(20) PRIMARY KEY,
    season_code character varying(10) NOT NULL,
    team_id character varying(10) NOT NULL,
    games_played double precision,
    minutes double precision,
    points smallint,
    two_points_made smallint,
    two_points_attempted smallint,
    three_points_made smallint,
    three_points_attempted smallint,
    free_throws_made smallint,
    free_throws_attempted smallint,
    offensive_rebounds smallint,
    defensive_rebounds smallint,
    total_rebounds smallint,
    assists smallint,
    steals smallint,
    turnovers smallint,
    blocks_favour smallint,
    blocks_against smallint,
    fouls_committed smallint,
    fouls_received smallint,
    valuation smallint,
    minutes_per_game double precision,
    points_per_game double precision,
    two_points_made_per_game double precision,
    two_points_attempted_per_game double precision,
    two_points_percentage double precision,
    three_points_made_per_game double precision,
    three_points_attempted_per_game double precision,
    three_points_percentage double precision,
    free_throws_made_per_game double precision,
    free_throws_attempted_per_game double precision,
    free_throws_percentage double precision,
    offensive_rebounds_per_game double precision,
    defensive_rebounds_per_game double precision,
    total_rebounds_per_game double precision,
    assists_per_game double precision,
    steals_per_game double precision,
    turnovers_per_game double precision,
    blocks_favour_per_game double precision,
    blocks_against_per_game double precision,
    fouls_committed_per_game double precision,
    fouls_received_per_game double precision,
    valuation_per_game double precision
);

COPY raw_teams
FROM
	'/Users/junn/Documents/codes/euroleague_dw/data/teams.csv' DELIMITER ',' CSV HEADER;